# Generated by Django 5.0.6 on 2024-07-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "用户"), (2, "管理员")], default=1, verbose_name="角色"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="TOKEN"
                    ),
                ),
            ],
        ),
    ]
